"""
backend/routes/telegram_routes.py

Telegram account linking: verifies 6-digit codes generated by the bot.
The bot generates the code (via /start command) and stores it in Supabase.
The user enters the code in the frontend, which calls this endpoint.
"""

from datetime import datetime, timezone

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel, Field

from auth import get_current_user_id
from db import get_supabase

router = APIRouter()



class LinkCode(BaseModel):
    code: str = Field(..., min_length=6, max_length=6, pattern=r"^\d{6}$")


@router.post("/verify")
def verify_link_code(
    body: LinkCode,
    user_id: str = Depends(get_current_user_id),
):
    """
    Verify a 6-digit Telegram link code.
    Links the authenticated user's Supabase account to their Telegram chat_id.

    Security:
    - Code must be unused and not expired (10-minute window)
    - user_id comes from JWT — cannot be spoofed
    - Code is marked used immediately after successful link
    """
    supabase = get_supabase()
    now = datetime.now(timezone.utc).isoformat()

    # Find a valid, unused, non-expired code
    resp = (
        supabase.table("telegram_link_codes")
        .select("*")
        .eq("code", body.code)
        .eq("used", False)
        .gte("expires_at", now)
        .execute()
    )

    if not resp.data:
        raise HTTPException(
            status_code=400,
            detail="Invalid or expired code. Please send /start to the bot again.",
        )

    link_record = resp.data[0]
    chat_id: int = link_record["telegram_chat_id"]

    # Check if this chat_id is already linked to a different account
    existing = (
        supabase.table("users")
        .select("id, email")
        .eq("telegram_chat_id", chat_id)
        .execute()
    )
    if existing.data and existing.data[0]["id"] != user_id:
        raise HTTPException(
            status_code=409,
            detail="This Telegram account is already linked to a different JobPulse account.",
        )

    # Link the user
    supabase.table("users").update({"telegram_chat_id": chat_id}).eq(
        "id", user_id
    ).execute()

    # Mark the code as used (prevent replay)
    supabase.table("telegram_link_codes").update({"used": True}).eq(
        "id", link_record["id"]
    ).execute()

    return {"success": True, "telegram_chat_id": chat_id}


@router.delete("/unlink")
def unlink_telegram(user_id: str = Depends(get_current_user_id)):
    """Remove the Telegram link from the authenticated user's account."""
    supabase = get_supabase()
    supabase.table("users").update({"telegram_chat_id": None}).eq(
        "id", user_id
    ).execute()
    return {"success": True}


@router.get("/status")
def get_telegram_status(user_id: str = Depends(get_current_user_id)):
    """Check if the user has a Telegram account linked."""
    supabase = get_supabase()
    resp = (
        supabase.table("users")
        .select("telegram_chat_id, notification_threshold, notification_frequency")
        .eq("id", user_id)
        .execute()
    )
    if not resp.data:
        return {"linked": False}
    user = resp.data[0]
    return {
        "linked": user["telegram_chat_id"] is not None,
        "notification_threshold": user["notification_threshold"],
        "notification_frequency": user["notification_frequency"],
    }
